services:
  eurekaserver:
    build: ./eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 10s

  configserver:
    build: ./configserver
    container_name: configserver
    ports:
      - "9999:9999"
    healthcheck:
      test: "curl --fail --silent localhost:9999/actuator/health | grep UP || exit 1"
      interval: 10s

  classification-ms:
    build: ./classification-microservice
    container_name: classification-ms
    ports:
      - "8086:8086"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
      # si ton microservice utilise un profil
      # - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8086/actuator/health | grep UP || exit 1"
      interval: 10s
  gatewayserver:
    build: ./gatewayserver
    container_name: gatewayserver
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
    depends_on:
     eurekaserver:
      condition: service_healthy
  classification-ms2:
    build: ./classification-microservice
    container_name: classification-ms2
    ports:
      - "8084:8086"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
      # si ton microservice utilise un profil
      # - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health | grep UP || exit 1"
      interval: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
  pays-ms:
    build: ./pays
    container_name: pays-ms
    ports:
      - "8085:8085"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
      # si ton microservice utilise un profil
      # - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      classification-ms:
        condition: service_healthy